=== ANDYGT40/rickkas7.github.io/pinInfo/pinData.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- simple types -->
<xs:element name="pinNumber" type="xs:int"/>
<xs:element name="pinName" type="xs:string"/>
<xs:element name="pinAltName" type="xs:string"/>
<xs:element name="pinDescription" type="xs:string"/>
<xs:element name="pinIsIO" type="xs:boolean"/>
<xs:element name="pin5VTolerant" type="xs:string"/>
<xs:element name="pinDigitalRead" type="xs:string"/>
<xs:element name="pinDigitalWrite" type="xs:string"/>
<xs:element name="pinAnalogRead" type="xs:string"/>
<xs:element name="pinAnalogWriteDAC" type="xs:string"/>
<xs:element name="pinAnalogWritePWM" type="xs:string"/>
<xs:element name="pinTone" type="xs:string"/>
<xs:element name="pinAttachInterrupt" type="xs:string"/>
<xs:element name="pinSerial" type="xs:string"/>
<xs:element name="pinSPI" type="xs:string"/>
<xs:element name="pinI2C" type="xs:string"/>
<xs:element name="pinI2S" type="xs:string"/>
<xs:element name="pinCAN" type="xs:string"/>

<xs:element name="detailLabel" type="xs:string"/>
<xs:element name="detailTag" type="xs:string"/>
<xs:element name="detailSearchable" type="xs:boolean"/>
<xs:element name="detailTrue" type="xs:string"/>
<xs:element name="detailFalse" type="xs:string"/>
<xs:element name="detailEmpty" type="xs:string"/>

<!-- attributes -->

<!-- complex types -->

<xs:element name="pinData">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="pin" minOccurs="0" maxOccurs="9999"/>
			<xs:element ref="detail" minOccurs="0" maxOccurs="9999"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>


<xs:element name="pin">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="pinNumber" minOccurs="1" maxOccurs="1"/>
			<xs:element ref="pinName" minOccurs="1" maxOccurs="1"/>
			<xs:element ref="pinAltName" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pinDescription" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pinIsIO" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pin5VTolerant" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pinDigitalRead" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pinDigitalWrite" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pinAnalogRead" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pinAnalogWriteDAC" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pinAnalogWritePWM" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pinTone" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pinAttachInterrupt" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pinSerial" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pinSPI" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pinI2C" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pinI2S" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="pinCAN" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="detail">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="detailLabel" minOccurs="1" maxOccurs="1"/>
			<xs:element ref="detailTag" minOccurs="1" maxOccurs="1"/>
			<xs:element ref="detailSearchable" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="detailTrue" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="detailFalse" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="detailEmpty" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>


</xs:schema>

=== ANDYGT40/rickkas7.github.io/pinInfo/pinData.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pinData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pinData.xsd">
	<pin>
		<pinNumber>1</pinNumber>
		<pinName>VIN</pinName>
		<pinDescription>Power in 3.3V to 5.5 VDC. Or power out (when powered by USB), 4.5 VDC at 1A maximum.</pinDescription>
		<pinIsIO>false</pinIsIO>
		<pin5VTolerant>Yes.</pin5VTolerant>
	</pin>
	<pin>
		<pinNumber>2</pinNumber>
		<pinName>GND</pinName>
		<pinDescription>Ground. There are two GND pins, only one needs to be connected.</pinDescription>
		<pinIsIO>false</pinIsIO>
	</pin>
	<pin>
		<pinNumber>3</pinNumber>
		<pinName>TX</pinName>
		<pinDescription>Serial1 TX (transmitted data), GPIO.</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>false</pinAnalogRead>
		<pinAnalogWritePWM>true</pinAnalogWritePWM>
		<pinTone>true</pinTone>
		<pinAttachInterrupt>true</pinAttachInterrupt>
		<pinSerial>TX. Use Serial1 object.</pinSerial>
	</pin>
	<pin>
		<pinNumber>4</pinNumber>
		<pinName>RX</pinName>
		<pinDescription>Serial1 RX (received data), GPIO.</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>false</pinAnalogRead>
		<pinAnalogWritePWM>true</pinAnalogWritePWM>
		<pinTone>true</pinTone>
		<pinAttachInterrupt>true</pinAttachInterrupt>
		<pinSerial>RX. Use Serial1 object. Is 5V tolerant.</pinSerial>
	</pin>
	<pin>
		<pinNumber>5</pinNumber>
		<pinName>WKP</pinName>
		<pinAltName>A7</pinAltName>
		<pinDescription>WKP/A7 Wakeup (active high), analog in, GPIO</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>true</pinAnalogRead>
		<pinAnalogWriteDAC>false</pinAnalogWriteDAC>
		<pinAnalogWritePWM>true</pinAnalogWritePWM>
		<pinTone>true</pinTone>
		<pinAttachInterrupt>true</pinAttachInterrupt>
	</pin>
	<pin>
		<pinNumber>6</pinNumber>
		<pinName>DAC</pinName>
		<pinAltName>A6</pinAltName>		
		<pinDescription>DAC/A6 True analog out, analog in, GPIO</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>false</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>true</pinAnalogRead>
		<pinAnalogWriteDAC>true</pinAnalogWriteDAC>
		<pinAnalogWritePWM>false</pinAnalogWritePWM>
		<pinTone>true</pinTone>
		<pinAttachInterrupt>Yes. D3 and DAC/A6 share the same interrupt handler.</pinAttachInterrupt>
	</pin>
	<pin>
		<pinNumber>7</pinNumber>
		<pinName>A5</pinName>
		<pinDescription>A5 Analog in, GPIO, SPI</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>true</pinAnalogRead>
		<pinAnalogWriteDAC>false</pinAnalogWriteDAC>
		<pinAnalogWritePWM>Yes. D2 and A5 share the same PWM channel and the PWM duty cycle is set for both.</pinAnalogWritePWM>
		<pinTone>Yes. D2 and A5 share the same PWM channel and only one frequency can be set for both.</pinTone>
		<pinAttachInterrupt>false</pinAttachInterrupt>
		<pinSPI>MOSI. Use SPI object.</pinSPI>
	</pin>
	<pin>
		<pinNumber>8</pinNumber>
		<pinName>A4</pinName>
		<pinDescription>A4 Analog in, GPIO, SPI</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>true</pinAnalogRead>
		<pinAnalogWriteDAC>false</pinAnalogWriteDAC>
		<pinAnalogWritePWM>Yes. D3 and A4 share the same PWM channel and the PWM duty cycle is set for both.</pinAnalogWritePWM>
		<pinTone>Yes. D3 and A4 share the same PWM channel and only one frequency can be set for both.</pinTone>
		<pinAttachInterrupt>Yes. D1 and A4 share the same interrupt handler.</pinAttachInterrupt>
		<pinSPI>MISO. Use SPI object.</pinSPI>
	</pin>
	<pin>
		<pinNumber>9</pinNumber>
		<pinName>A3</pinName>
		<pinDescription>A3 True analog out, analog in, GPIO, SPI</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>false</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>true</pinAnalogRead>
		<pinAnalogWriteDAC>true</pinAnalogWriteDAC>
		<pinAnalogWritePWM>false</pinAnalogWritePWM>
		<pinTone>false</pinTone>
		<pinAttachInterrupt>Yes. D2, A0, and A3 share the same interrupt handler.</pinAttachInterrupt>
		<pinSPI>SCK. Use SPI object.</pinSPI>
	</pin>
	<pin>
		<pinNumber>10</pinNumber>
		<pinName>A2</pinName>
		<pinDescription>A2 Analog in, GPIO</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>true</pinAnalogRead>
		<pinAnalogWriteDAC>false</pinAnalogWriteDAC>
		<pinAnalogWritePWM>false</pinAnalogWritePWM>
		<pinTone>false</pinTone>
		<pinAttachInterrupt>true</pinAttachInterrupt>
		<pinSPI>SS. Use SPI object.</pinSPI>
	</pin>
	<pin>
		<pinNumber>11</pinNumber>
		<pinName>A1</pinName>
		<pinDescription>A1 Analog in, GPIO</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>true</pinAnalogRead>
		<pinAnalogWriteDAC>false</pinAnalogWriteDAC>
		<pinAnalogWritePWM>false</pinAnalogWritePWM>
		<pinTone>false</pinTone>
		<pinAttachInterrupt>Yes. D4 and A1 share the same interrupt handler.</pinAttachInterrupt>
	</pin>
	<pin>
		<pinNumber>12</pinNumber>
		<pinName>A0</pinName>
		<pinDescription>A0 Analog in, GPIO</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>true</pinAnalogRead>
		<pinAnalogWriteDAC>false</pinAnalogWriteDAC>
		<pinAnalogWritePWM>false</pinAnalogWritePWM>
		<pinTone>false</pinTone>
		<pinAttachInterrupt>Yes. D2, A0, and A3 share the same interrupt handler.</pinAttachInterrupt>
	</pin>
	<pin>
		<pinNumber>13</pinNumber>
		<pinName>D0</pinName>
		<pinDescription>D0 GPIO, I2C, Serial2</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>false</pinAnalogRead>
		<pinAnalogWritePWM>true</pinAnalogWritePWM>
		<pinTone>true</pinTone>
		<pinAttachInterrupt>false</pinAttachInterrupt>
		<pinI2C>SDA. Use Wire object. Use 1.5K to 10K external pull-up resistor. Is 5V tolerant.</pinI2C>
	</pin>
	<pin>
		<pinNumber>14</pinNumber>
		<pinName>D1</pinName>
		<pinDescription>D1 GPIO, I2C, Serial2</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>false</pinAnalogRead>
		<pinAnalogWritePWM>true</pinAnalogWritePWM>
		<pinTone>true</pinTone>
		<pinAttachInterrupt>Yes. D1 and A4 share the same interrupt handler.</pinAttachInterrupt>
		<pinI2C>SCL. Use Wire object. Use 1.5K to 10K external pull-up resistor. Is 5V tolerant.</pinI2C>
		<pinCAN>TX</pinCAN>
	</pin>
	<pin>
		<pinNumber>15</pinNumber>
		<pinName>D2</pinName>
		<pinDescription>D2 GPIO, SPI1</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>false</pinAnalogRead>
		<pinAnalogWritePWM>Yes. D2 and A5 share the same PWM channel and the PWM duty cycle is set for both.</pinAnalogWritePWM>
		<pinTone>Yes. D2 and A5 share the same PWM channel and only one frequency can be set for both.</pinTone>
		<pinAttachInterrupt>Yes. D2, A0, and A3 share the same interrupt handler.</pinAttachInterrupt>
		<pinSPI>MOSI. Use SPI1 object.</pinSPI>
		<pinI2S>SD</pinI2S>
		<pinCAN>RX</pinCAN>
	</pin>
	<pin>
		<pinNumber>16</pinNumber>
		<pinName>D3</pinName>
		<pinDescription>D3 GPIO, SPI1</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>false</pinAnalogRead>
		<pinAnalogWritePWM>Yes. D3 and A4 share the same PWM channel and the PWM duty cycle is set for both.</pinAnalogWritePWM>
		<pinTone>Yes. D3 and A4 share the same PWM channel and only one frequency can be set for both.</pinTone>
		<pinAttachInterrupt>Yes. D3 and DAC/A6 share the same interrupt handler.</pinAttachInterrupt>
		<pinSPI>MISO. Use SPI1 object.</pinSPI>
	</pin>
	<pin>
		<pinNumber>17</pinNumber>
		<pinName>D4</pinName>
		<pinDescription>D4 GPIO, SPI1</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>false</pinAnalogRead>
		<pinAnalogWritePWM>false</pinAnalogWritePWM>
		<pinTone>false</pinTone>
		<pinAttachInterrupt>Yes. D4 and A1 share the same interrupt handler.</pinAttachInterrupt>
		<pinSPI>SCK. Use SPI1 object.</pinSPI>
		<pinI2S>SCK</pinI2S>
	</pin>
	<pin>
		<pinNumber>18</pinNumber>
		<pinName>D5</pinName>
		<pinDescription>D5 GPIO, SPI1</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
		<pinDigitalWrite>true</pinDigitalWrite>
		<pinAnalogRead>false</pinAnalogRead>
		<pinAnalogWritePWM>false</pinAnalogWritePWM>
		<pinTone>false</pinTone>
		<pinAttachInterrupt>true</pinAttachInterrupt>
		<pinSPI>SS. Use SPI1 object.</pinSPI>
		<pinI2S>WS</pinI2S>
	</pin>
	<pin>
		<pinNumber>19</pinNumber>
		<pinName>D6</pinName>
		<pinDescription>D6 GPIO</pinDescription>
		<pinIsIO>true</pinIsIO>
		<pin5VTolerant>true</pin5VTolerant>
		<pinDigitalRead>true</pinDigitalRead>
